[loggers]
keys=root,rosout
[handlers]
keys=fileHandler,streamHandler
[formatters]
keys=defaultFormatter
[logger_root]
level=@LEVEL@
handlers=fileHandler
[logger_rosout]
level=@LEVEL@
handlers=streamHandler
propagate=1
qualname=rosout
[handler_fileHandler]
class=handlers.RotatingFileHandler
level=@LEVEL@
formatter=defaultFormatter
args=(os.environ['ROS_LOG_FILENAME'],'a',int(os.environ['ROS_LOG_MAX_BYTES']),int(os.environ['ROS_LOG_BACKUP_COUNT']))
[handler_streamHandler]
class=rosgraph.roslogging.RosStreamHandler
level=@LEVEL@
formatter=defaultFormatter
args=(True,)
[formatter_defaultFormatter]
format=[%(name)s][%(levelname)s] %(asctime)s: %(message)s
