cmake_minimum_required(VERSION 3.0.2)
project(physical_nav)
find_package(catkin REQUIRED COMPONENTS rospy std_msgs)
catkin_package()
catkin_install_python(PROGRAMS scripts/physical_consistency_node.py scripts/physical_ros_gateway.py DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(FILES scripts/physical_consistency.py DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(DIRECTORY launch config DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
